spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=kamiya

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG
logging.level.root=INFO
logging.level.com.portfolio.user=DEBUG
#logging.file.name=logs/app.log
#logging.file.name=logs/app_%d{yyyy-MM-dd_HH-mm-ss}.log
logging.config=logback-spring.xml
#logging.logback.rollingpolicy.file-name-pattern=logs/app_%d{yyyy-MM-dd_HH-mm-ss}.%i.log
logging.structured.format.console=ecs

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}